# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57dc31daa9a80f14084735f85847a72ba507bf3da807d63f2860efd796ad0c3bfeb3db9ed58ec616dcba9bf9516583c33f71a302655ff958b3e393f44ea57290

test:
  secret_key_base: 8f4c6f1ad8aac0a3d73326144547fda8bb38db91c8d7d4ebfa8a98e2582b42d7ba396f25b9c98fb3090dde8635b714077e53d67ca95e8a932587f40e2fa1a504

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
